[package]
name = "logistic_regression"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deltaml = { path = "../../../delta", features = ["classical"] }
tokio = { workspace = true, features = ["full"] }
