[package]
name = "mnist"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deltaml = { path = "../../../delta", features = ["metal"] }
tokio = { workspace = true, features = ["full"] }