[package]
name = "support_vector_machines"
version = "0.1.0"
edition = "2024"

[dependencies]
deltaml = { path = "../../../delta", features = ["classical_ml"] }
tokio = { workspace = true, features = ["full"] }
