[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deltaml = { path = "../../../delta" }
tokio = { workspace = true, features = ["full"] }
plotters = "0.3.1"
