[package]
name = "cifar100"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
deltaml = { path = "../../../delta", features = ["deep_learning", "vision"] }
tokio = { workspace = true, features = ["full"] }
